app/Http/routes.php
<?php

Route::group(["middleware" => ["web"]], function() {

	Route::get("/", ["as" => "home", "uses" => "HomeController@getHome"]);

	Route::group(["middleware" => ["guest"]], function() {

		Route::post("/login", ["as" => "login", "uses" => "AuthController@postLogin"]);

	});

	Route::group(["middleware" => ["auth"]], function() {

		Route::get("/dashboard", ["as" => "dashboard", "uses" => "DashboardController@getDashboard"]);

		Route::get("/dashboard/current/change", ["as" => "dashboard.current", "uses" => "DashboardController@getCurrentBrewery"]);
		Route::post("/dashboard/current/set", ["as" => "dashboard.current.set", "uses" => "DashboardController@postCurrentBrewery"]);
		
		Route::get("/dashboard/plans", ["as" => "dashboard.plans", "uses" => "PlannedBatchManagementSystemController@getPlans"]);
		Route::post("/checkfile", ["as" => "checkfile", "uses" => "PlannedBatchManagementSystemController@checkIfOutFileHasBeenGenerated"]);

		$managementable_models = ["vat", "fermenter", "brewery", "ongoing.batch", "planned.batch"];
		foreach($managementable_models as $model) {
			getManagementRoutes($model);
		}

		Route::get("/dashboard/batch/add", ["as" => "dashboard.batch.add", "uses" => "PlannedBatchManagementSystemController@getAddForm"]);
		Route::post("/dashboard/batch/add", ["as" => "dashboard.batch.add.post", "uses" => "PlannedBatchManagementSystemController@postAdd"]);
		
		Route::post("/logout", ["as" => "logout", "uses" => "AuthController@postLogout"]);

		Route::group(["middleware" => ["admin"]], function() {
			Route::get("/dashboard/admin", ["as" => "dashboard.admin", "uses" => "DashboardController@getAdminDashboard"]);

			$managementable_models = ["user", "style"];
			foreach($managementable_models as $model) {
				getManagementRoutes($model);
			}
		});

	});

});

function getManagementRoutes($model) {
	$controller_name = str_replace(".", "", ucfirst($model));

	Route::get("/dashboard/". $model, [
		"as" => "dashboard.". $model .".list",
		"uses" => $controller_name ."ManagementSystemController@getList"
	]);
	Route::get("/dashboard/". $model ."/{id}", [
		"as" => "dashboard.". $model .".view",
		"uses" => $controller_name ."ManagementSystemController@getView"
	])->where("id", "[0-9]+");
	Route::get("/dashboard/". $model ."/add", [
		"as" => "dashboard.". $model .".add",
		"uses" => $controller_name ."ManagementSystemController@getAddForm"
	]);
	Route::post("/dashboard/". $model ."/add", [
		"as" => "dashboard.". $model .".add.post",
		"uses" => $controller_name ."ManagementSystemController@postAdd"
	]);
	Route::get("/dashboard/". $model ."/edit/{id}", [
		"as" => "dashboard.". $model .".edit",
		"uses" => $controller_name ."ManagementSystemController@getEditForm"
	])->where("id", "[0-9]+");
	Route::post("/dashboard/". $model ."/edit/{id}", [
		"as" => "dashboard.". $model .".edit.post",
		"uses" => $controller_name ."ManagementSystemController@postEdit"
	])->where("id", "[0-9]+");
	Route::get("/dashboard/". $model ."/delete/{id}", [
		"as" => "dashboard.". $model .".delete",
		"uses" => $controller_name ."ManagementSystemController@getDeleteConfirm"
	])->where("id", "[0-9]+");
	Route::post("/dashboard/". $model ."/delete/{id}", [
		"as" => "dashboard.". $model .".delete.post",
		"uses" => $controller_name ."ManagementSystemController@postDelete"
	])->where("id", "[0-9]+");
	Route::get("/dashboard/". $model ."/find", [
		"as" => "dashboard.". $model .".find",
		"uses" => $controller_name ."ManagementSystemController@getSearchJSON"
	]);
}

app/Models/Brewery.php
<?php 

namespace App\Models;

use App\Http\Interfaces\ManagementableObjectInterface;
use App\Http\Requests\AddEditBreweryRequest;
use App\Services\BreweryManagementService;
use Carbon\Carbon;

class Brewery extends Model implements ManagementableObjectInterface {

	protected $table = "breweries";
	protected $fillable = ["name", "user_id"];

	public function batches() {
		return $this->hasMany(Batch::class);
	}

	public function ongoing_batches() {
		return $this->batches()->where("brewing_date", "<=", Carbon::now());
	}

	public function planned_batches() {
		return $this->batches()->where("brewing_date", ">", Carbon::now());
	}

	public function vats() {
		return $this->hasMany(Vat::class);
	}

	public function fermenters() {
		return $this->hasMany(Fermenter::class);
	}

	public function getVatsCountAttribute() {
		return $this->vats->count();
	}

	public function getFermentersCountAttribute() {
		return $this->fermenters->count();
	}

	public function getBrewedBatchesCountAttribute() {
		return $this->batches->count();
	}

	public function getOngoingBatchesCountAttribute() {
		return $this->ongoing_batches->count();
	}

	public function getPlannedBatchesCountAttribute() {
		return $this->planned_batches->count();
	}

	public function getRequest() {
		return new AddEditBreweryRequest();
	}

	public function getService() {
		return new BreweryManagementService();
	}

}

app/Http/Controllers/DashboardController.php
<?php 

namespace App\Http\Controllers;

use Auth, Redirect, Session;
use Illuminate\Http\Request;

class DashboardController extends Controller {
	
	public static function getDashboard() {
		if(is_null(Auth::user()->getCurrentBrewery())) {
			return view("dashboard.current");
		}
		return view("dashboard.dashboard");
	}

	public function getCurrentBrewery() {
		return view("dashboard.current");
	}

	public function postCurrentBrewery(Request $request) {
		$brewery = Auth::user()->breweries->where("id", (int) $request->input("brewery_id"))->first();

		if(is_null($brewery)) {
			Session::flash("error", "Nie masz praw do zarządzania wybranych browarem");
			return self::getDashboard();
		}

		Auth::user()->update(["current_brewery_id" => $brewery->id]);

		Session::flash("success", "Wybrano <strong>". $brewery->name ."</strong>.");
		return Redirect::route("dashboard");
	}

	public static function getAdminDashboard() {
		return view("dashboard.admin");
	}

}

resources/views/dashboard/admin.blade.php
@extends("dashboard.root")

@section("dashboard.container")

	<h1>Administracja</h1>
	<hr>

	<div class="row">
		<div class="dashboard-tile add-new col-md-4 col-sm-6 col-xs-12" data-url="{{ route('dashboard.user.list') }}">
			użytkownicy
		</div>
		<div class="dashboard-tile add-new col-md-4 col-sm-6 col-xs-12" data-url="{{ route('dashboard.style.list') }}">
			style piwne
		</div>
	</div>
				
	<hr>

@endsection

resources/views/dashboard/current.blade.php
@extends("dashboard.root")

@section("dashboard.container")
	@include("dashboard.splashscreen")
@stop

resources/views/dashboard/dashboard.blade.php
@extends("dashboard.root")

@section("dashboard.container")

	<div class="row">
		<div class="col-lg-3 col-md-6">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<div class="text-right">
						<div>kadzi zacierno-warzelnych</div>
						<div class="huge">{{ $current_brewery->vats_count }}</div>
					</div>
				</div>
				<a href="{{ route('dashboard.vat.list') }}">
					<div class="panel-footer">
						<span class="pull-left">zarządzaj</span>
						<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
						<div class="clearfix"></div>
					</div>
				</a>
			</div>
		</div>
		<div class="col-lg-3 col-md-6">
			<div class="panel panel-green">
				<div class="panel-heading">
					<div class="text-right">
						<div>pojemników fermentacyjnych</div>
						<div class="huge">{{ $current_brewery->fermenters_count }}</div>
					</div>
				</div>
				<a href="{{ route('dashboard.fermenter.list') }}">
					<div class="panel-footer">
						<span class="pull-left">zarządzaj</span>
						<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
						<div class="clearfix"></div>
					</div>
				</a>
			</div>
		</div>
		<div class="col-lg-3 col-md-6">
			<div class="panel panel-yellow">
				<div class="panel-heading">
					<div class="text-right">
						<div>warek aktualnie w produkcji</div>
						<div class="huge">{{ $current_brewery->ongoing_batches_count }}</div>
					</div>
				</div>
				<a href="{{ route('dashboard.ongoing.batch.list') }}">
					<div class="panel-footer">
						<span class="pull-left">zarządzaj</span>
						<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
						<div class="clearfix"></div>
					</div>
				</a>
			</div>
		</div>
		<div class="col-lg-3 col-md-6">
			<div class="panel panel-red">
				<div class="panel-heading">
					<div class="text-right">
						<div>warek zaplanowano</div>
						<div class="huge">{{ $current_brewery->planned_batches_count }}</div>
					</div>
				</div>
				<a href="{{ route('dashboard.planned.batch.list') }}">
					<div class="panel-footer">
						<span class="pull-left">zarządzaj</span>
						<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
						<div class="clearfix"></div>
					</div>
				</a>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-6 col-lg-offset-6 col-md-12">
			<div class="panel panel-green">
				<div class="panel-heading">
					<div class="text-right">
						<div class="huge">
							<a href="{{ route('dashboard.batch.add') }}">
								<i class="fa fa-plus" style="color: White;"></i>
							</a>
						</div>
					</div>
				</div>
				<a href="{{ route('dashboard.batch.add') }}">
					<div class="panel-footer">
						<span class="pull-left">dodaj nową warkę do planu produkcji</span>
						<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
						<div class="clearfix"></div>
					</div>
				</a>
			</div>
		</div>
	</div>
				
	<hr>

@endsection

resources/views/dashboard/plans.blade.php
@extends("dashboard.root")

@section("dashboard.container")

	<h1>Planowanie fermentacji</h1>
	<hr>

	<div class="row well">
		Zaplanowane warki: 
		@foreach($batches as $batch)
		<div class="legend planned-day occupied" data-batch-id="{{ $batch->id }}">
				{{ $batch->id }}
		</div>
		@endforeach
	</div>

	@foreach($fermenters as $fermenter)
		<div class="fermenter well">
			<h3>{{ $fermenter["fermenter"]->name }}</h3>
			@foreach($fermenter["days"] as $day)
				<div class="planned-day {{ $day["value"] ? "occupied" : "free" }}" title="{{ $fermenter["today"]->addDay()->format("d.m.Y") }}" data-batch-id="{{ $day["value"] ? $day["batch"] : "" }}" data-toggle="tooltip" data-placement="top">
					{{ $day["value"] ? $day["batch"] : "&nbsp;" }}
				</div>
			@endforeach
		</div>
	@endforeach

@endsection

resources/views/dashboard/root.blade.php
@extends("root")

@section("styles")
	{!! Html::style("css/dashboard.css") !!}
@stop

@section("navbar")
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Przełącz nawigację</span>
					<i class="fa fa-bars"></i>
				</button>
				<a class="navbar-brand" href="{{ route('dashboard') }}">SPMiT</a>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					@if($current_brewery)
						<li><a href="{{ route("dashboard.fermenter.list") }}">browar</a></li>
						<li><a href="{{ route("dashboard.plans") }}">plan produkcji</a></li>
						<li><a href="{{ route('dashboard.batch.add') }}"><i class="fa fa-plus"></i></a></li>
						@if($user->isAdmin())
						<li><a href="{{ route("dashboard.admin") }}">administracja</a></li>
						@endif
					@endif
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li class="active">
						<a href="{{ route('dashboard.current') }}">
							@if($current_brewery) {{ $current_brewery->name }} <i class="fa fa-refresh"></i> @else [wybierz browar] @endif
						</a>
					</li>
					<li><a href="#"><i class="fa fa-user"></i> {{ Auth::user()->name }}</a></li>
					<li><a id="logout"><i class="fa fa-sign-out"></i></a></li>
					<form action="{{ route('logout') }}" method="post" class="hidden" id="logout-form">
						<input type="hidden" name="_token" value="{{ csrf_token() }}">
						<input type="submit">
					</form>
				</ul>
			</div>
		</div>
	</nav>
@stop

@section("container")
	@include("alerts")
	@if($current_brewery || Request::route()->getName() == "dashboard.brewery.add")
		@yield("dashboard.container")
	@else
		@include("dashboard.splashscreen")
	@endif
@stop

@section("scripts")
	{!! Html::script("js/dashboard.js") !!}
@stop

resources/views/dashboard/splashscreen.blade.php
<div class="row">
	<h2>Wybierz browar</h2>

	@foreach($user->breweries as $brewery)
		<form action="{{ route('dashboard.current.set') }}" method="post" class="dashboard-tile change-current-brewery col-md-4 col-sm-6 col-xs-12">
			{{ $brewery->name }}
			<input type="hidden" name="_token" value="{{ csrf_token() }}">
			<input type="hidden" name="brewery_id" value="{{ $brewery->id }}">
			<input type="submit" class="hidden">
		</form>
	@endforeach

	<div class="dashboard-tile add-new col-md-4 col-sm-6 col-xs-12" data-url="{{ route('dashboard.brewery.add') }}">
		<i class="fa fa-plus"></i> dodaj nowy
	</div>
</div>

resources/views/dashboard/wait.blade.php
@extends("dashboard.root")

@section("dashboard.container")

	<h1>Planowanie fermentacji</h1>
	<hr>

	<div id="view-container" class="text-center">
		<input type="hidden" id="_token" value="{{ csrf_token() }}">
		<i id="preloader" class="fa fa-refresh fa-spin fa-4x" data-checkfile={{ route("checkfile") }} data-batch-id={{ $batch_id }}></i>
		<hr>
		<div class="alert alert-info">Trwa obliczanie...</div>
	</div>


@endsection