app/Http/routes.php
<?php

Route::group(["middleware" => ["web"]], function() {

	Route::get("/", ["as" => "home", "uses" => "HomeController@getHome"]);

	Route::group(["middleware" => ["guest"]], function() {

		Route::post("/login", ["as" => "login", "uses" => "AuthController@postLogin"]);

	});

	Route::group(["middleware" => ["auth"]], function() {

		Route::get("/dashboard", ["as" => "dashboard", "uses" => "DashboardController@getDashboard"]);

		Route::get("/dashboard/current/change", ["as" => "dashboard.current", "uses" => "DashboardController@getCurrentBrewery"]);
		Route::post("/dashboard/current/set", ["as" => "dashboard.current.set", "uses" => "DashboardController@postCurrentBrewery"]);
		
		Route::get("/dashboard/plans", ["as" => "dashboard.plans", "uses" => "PlannedBatchManagementSystemController@getPlans"]);
		Route::post("/checkfile", ["as" => "checkfile", "uses" => "PlannedBatchManagementSystemController@checkIfOutFileHasBeenGenerated"]);

		$managementable_models = ["vat", "fermenter", "brewery", "ongoing.batch", "planned.batch"];
		foreach($managementable_models as $model) {
			getManagementRoutes($model);
		}

		Route::get("/dashboard/batch/add", ["as" => "dashboard.batch.add", "uses" => "PlannedBatchManagementSystemController@getAddForm"]);
		Route::post("/dashboard/batch/add", ["as" => "dashboard.batch.add.post", "uses" => "PlannedBatchManagementSystemController@postAdd"]);
		
		Route::post("/logout", ["as" => "logout", "uses" => "AuthController@postLogout"]);

		Route::group(["middleware" => ["admin"]], function() {
			Route::get("/dashboard/admin", ["as" => "dashboard.admin", "uses" => "DashboardController@getAdminDashboard"]);

			$managementable_models = ["user", "style"];
			foreach($managementable_models as $model) {
				getManagementRoutes($model);
			}
		});

	});

});

function getManagementRoutes($model) {
	$controller_name = str_replace(".", "", ucfirst($model));

	Route::get("/dashboard/". $model, [
		"as" => "dashboard.". $model .".list",
		"uses" => $controller_name ."ManagementSystemController@getList"
	]);
	Route::get("/dashboard/". $model ."/{id}", [
		"as" => "dashboard.". $model .".view",
		"uses" => $controller_name ."ManagementSystemController@getView"
	])->where("id", "[0-9]+");
	Route::get("/dashboard/". $model ."/add", [
		"as" => "dashboard.". $model .".add",
		"uses" => $controller_name ."ManagementSystemController@getAddForm"
	]);
	Route::post("/dashboard/". $model ."/add", [
		"as" => "dashboard.". $model .".add.post",
		"uses" => $controller_name ."ManagementSystemController@postAdd"
	]);
	Route::get("/dashboard/". $model ."/edit/{id}", [
		"as" => "dashboard.". $model .".edit",
		"uses" => $controller_name ."ManagementSystemController@getEditForm"
	])->where("id", "[0-9]+");
	Route::post("/dashboard/". $model ."/edit/{id}", [
		"as" => "dashboard.". $model .".edit.post",
		"uses" => $controller_name ."ManagementSystemController@postEdit"
	])->where("id", "[0-9]+");
	Route::get("/dashboard/". $model ."/delete/{id}", [
		"as" => "dashboard.". $model .".delete",
		"uses" => $controller_name ."ManagementSystemController@getDeleteConfirm"
	])->where("id", "[0-9]+");
	Route::post("/dashboard/". $model ."/delete/{id}", [
		"as" => "dashboard.". $model .".delete.post",
		"uses" => $controller_name ."ManagementSystemController@postDelete"
	])->where("id", "[0-9]+");
	Route::get("/dashboard/". $model ."/find", [
		"as" => "dashboard.". $model .".find",
		"uses" => $controller_name ."ManagementSystemController@getSearchJSON"
	]);
}

app/Models/BeerStyle.php
<?php 

namespace App\Models;

class BeerStyle extends Model {

	protected $table;
	protected $fillable = ["symbol", "name", "brewery_id", "abv_min", "abv_max", "og_min", "og_max", "fg_min", "fg_max", "ibu_min", "ibu_max", "srm_min", "srm_max"];
	public $timestamps = false;

	public function convertToPlato($value) {
		if(is_null($value)) {
			return null;
		}

		// based on scientific/chemistry mumbo-jumbo
		$result = -616.868;
		$result += 1111.14 * $value;
		$result -= 630.272 * pow($value, 2);
		$result += 135.997 * pow($value, 3);

		return $result > 0 ? number_format($result, 1) : 0;
	}

	public function getOgMinPlatoAttribute() {
		return $this->convertToPlato($this->og_min);
	}

	public function getOgMaxPlatoAttribute() {
		return $this->convertToPlato($this->og_max);
	}

	public function getFgMinPlatoAttribute() {
		return $this->convertToPlato($this->fg_min);
	}

	public function getFgMaxPlatoAttribute() {
		return $this->convertToPlato($this->fg_max);
	}

}

resources/views/cms/addedit.blade.php
@extends("dashboard.root")

@section("dashboard.container")

	<h1>@if($object->id) Edytujesz @else Dodajesz @endif {{ $item_name }}</h1>

	<form class="col-sm-10 col-sm-offset-1" method="POST">
		<input type="hidden" name="_token" value="{!! csrf_token() !!}">

		@foreach($fields as $field)
			<div class="form-input-row form-group">
				<label class="col-sm-2 small">{{ $field["label"] }}</label>
				<div class="col-sm-10">

					@if($field["type"] == "select")
						<select name="{{ $field["name"] }}" class="form-control">
							@if(isset($field["default_none"]) && $field["default_none"])
							<option value="">brak</option>
							@endif
							@foreach($field["options"] as $option)
							<option value="{{ $option->id }}" @if((old($field["name"]) ?: $field["value"]($object)) == $option->id) selected="selected" @endif data-min-blg="{{ $option->og_min_plato }}" data-max-blg="{{ $option->og_max_plato }}">{{ $option->name }}</option>
							@endforeach
						</select>
					@else
						<input name="{{ $field["name"] }}" type="text" class="form-control" placeholder="{{ $field["label"] }}" value="{{ old($field["name"]) ?: $field["value"]($object) }}" autocomplete="off">
					@endif

				</div>
			</div>
		@endforeach

		<div class="submit-add-edit btn-group open pull-right">
			<button type="submit" class="btn btn-success btn-lg">zapisz</button>
			<button type="submit" class="btn btn-success btn-lg"><i class="fa fa-chevron-right"></i></button>
		</div>
	</form>

@endsection

resources/views/cms/delete.blade.php
@extends("dashboard.root")

@section("dashboard.container")

	<h1>Usuwasz {{ $item_name }}: {{ $object->name }}</h1>

	<form class="col-sm-10 col-sm-offset-1" method="POST">
		<div class="alert alert-danger dashboard-alert">
			Usunięcie obiektu jest nieodwracalne. Musisz potwierdzić tę akcję.
		</div>

		<input type="hidden" name="_token" value="{!! csrf_token() !!}">

		<center>
			<div class="btn-group open ">
				<button type="submit" class="btn btn-danger btn-lg">usuń</button>
				<button type="submit" class="btn btn-danger btn-lg"><i class="fa fa-close"></i></button>
			</div>
		</center>
	</form>

@endsection

resources/views/cms/list.blade.php
@extends("dashboard.root")

@section("dashboard.container")

	<h1>{{ $title }}</h1>

	@if($description)
	<blockquote class="description">{!! $description !!}</blockquote>
	@endif

	<div class="dashboard-table-options">
		@if($allow_new_items)
			<div class="btn-group open pull-right">
				<a class="btn btn-success" href="{{ route('dashboard.'. $route .'.add') }}"><i class="fa fa-plus"></i></a>
				<a class="btn btn-success" href="{{ route('dashboard.'. $route .'.add') }}">dodaj nowy obiekt</a>
			</div>
		@endif
	</div>

	<table class="table table-striped table-hover table-condensed">
		<thead>
			@if($allow_ordinal_column)
			<th>#</th>
			@endif
			@foreach($columns as $column)
			<th>
				@if(isset($column["minmax"]) && $column["minmax"])
					@if($column["sortable"]) 
						@if($order != $column["name"]."_min-asc")
						<a href="?{{ http_build_query(Input::except('order')) }}&order={{ $column['name'] }}_min-asc"><i class="fa fa-angle-up"></i></a>
						@else
						<i class="fa fa-angle-up"></i>
						@endif

						@if($order != $column["name"]."_min-desc")
						<a href="?{{ http_build_query(Input::except('order')) }}&order={{ $column['name'] }}_min-desc"><i class="fa fa-angle-down"></i></a>
						@else
						<i class="fa fa-angle-down"></i>
						@endif
					@endif
					{!! $column["title"] !!}
					@if($column["sortable"]) 
						@if($order != $column["name"]."_max-asc")
						<a href="?{{ http_build_query(Input::except('order')) }}&order={{ $column['name'] }}_max-asc"><i class="fa fa-angle-up"></i></a>
						@else
						<i class="fa fa-angle-up"></i>
						@endif

						@if($order != $column["name"]."_max-desc")
						<a href="?{{ http_build_query(Input::except('order')) }}&order={{ $column['name'] }}_max-desc"><i class="fa fa-angle-down"></i></a>
						@else
						<i class="fa fa-angle-down"></i>
						@endif
					@endif
				@else
					{!! $column["title"] !!}
					@if($column["sortable"]) 
						@if($order != $column["name"]."-asc")
						<a href="?{{ http_build_query(Input::except('order')) }}&order={{ $column['name'] }}-asc"><i class="fa fa-angle-up"></i></a>
						@else
						<i class="fa fa-angle-up"></i>
						@endif

						@if($order != $column["name"]."-desc")
						<a href="?{{ http_build_query(Input::except('order')) }}&order={{ $column['name'] }}-desc"><i class="fa fa-angle-down"></i></a>
						@else
						<i class="fa fa-angle-down"></i>
						@endif
					@endif
				@endif
			</th>
			@endforeach
			@if($any_actions)
			<th class="text-right">opcje</th>
			@endif
		</thead>
		<tbody>
			@foreach($data as $value)
			<tr>
				@if($allow_ordinal_column)
				<td>{{ $allow_ordinal_column++ }}</td>
				@endif
				@foreach($columns as $column)
				<td>
					@if(isset($column["boolean"]) && $column["boolean"])
						@if($column["value"]($value))
							<i class="fa fa-check-square-o"></i>
						@else 
							<i class="fa fa-square-o"></i>
						@endif
					@elseif(isset($column["minmax"]) && $column["minmax"])
						@if(is_null($column["value"]($value)["min"]) && is_null($column["value"]($value)["max"]))
							n/d
						@else
							{!! $column["value"]($value)["min"] !!} - {!! $column["value"]($value)["max"] !!}
						@endif
					@else
					{!! $column["value"]($value) !!}
					@endif
				</td>
				@endforeach
				@if($any_actions)
					<td class="text-right">
						@if($allowed_actions["edit"])
						<div class="btn-group open">
							<a class="btn btn-sm btn-info" href="{{ route('dashboard.'. $route .'.edit', $value->id) }}"><i class="fa fa-pencil fa-lg"></i></a>
						</div>
						@endif
						@if($allowed_actions["delete"])
						<div class="btn-group open">
							<a class="btn btn-sm btn-danger" href="{{ route('dashboard.'. $route .'.delete', $value->id) }}"><i class="fa fa-close fa-lg"></i></a>
						</div>
						@endif
						@if($allowed_actions["preview"])
						<div class="btn-group open">
							<a class="btn btn-sm btn-success" href="{{ route('dashboard.'. $route .'.view', $value->id) }}"><i class="fa fa-eye fa-lg"></i></a>
						</div>
						@endif
					</td>
				@endif
			</tr>
			@endforeach
		</tbody>
	</table>

@endsection